spring.application.name=tms-backend

# Server Configuration
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/tms_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=142536
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret (Base64 encoded) and Expiration (24 hours)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Razorpay Configuration
razorpay.key.id=rzp_test_your_key_id
razorpay.key.secret=your_key_secret

# Firebase Configuration
firebase.config.path=src/main/resources/firebase-service-account.json

# Email Configuration (using Gmail SMTP as example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raunakchirania6@gmail.com
spring.mail.password=mihzrzsshokogpwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
